### ISSUE TITLE
new sandbox deleted the sample record

### ISSUE THREAD

**Issue by alexlancaster** [zenodraft/zenodo-upload-metadata-schema#3]
with the update to the sandbox.zenodo.org, looks like completely reinitialized the database, so the sample record:

https://sandbox.zenodo.org/records/1049232

is not your "All the fields" example anymore.  I currently can't even login to sandbox, after github authentication it redirects me to https://zenodo-rdm-qa.web.cern.ch/  maybe you too?

**Comment by alexlancaster** [comment]
OK, I was able to get back into the sandbox and re-up my ZENODO_SANDBOX_ACCESS_TOKEN.  The deposition _almost_ finishes but it fails on the uploading of the zip:

`  Error: Something went wrong on PUT to https://zenodo-rdm-qa.web.cern.ch/api/files/d8b2d879-ff12-414a-864f-57a9f6e98412/pypop.zip: 415 - UNSUPPORTED MEDIA TYPE
`

full log: https://github.com/alexlancaster/pypop/actions/runs/6512881796/job/17691391663#step:6:510

**Comment by jspaaks** [comment]
I just updated the _All the properties!_ record on Zenodo Sandbox ([link](https://sandbox.zenodo.org/record/24389)) but I needed to make some small changes for it to work, see #4. I also added examples for some more `relation` types in `related_identifiers`, see #2.
